targets:
  $default:
    builders:
      flutter_envify_generator|flutter_envify:
        enabled: True

builders:
  flutter_envify:
    import: "package:flutter_envify_generator/builder.dart"
    builder_factories: ["envifyBuilder"]
    build_extensions:
      .dart:
        - flutter_envify.g.dart
    build_to: cache
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
