name: flutter_envify
description: A better way to handle environment variables using `.env` file.
version: 1.0.0
homepage: https://github.com/tevfik1/flutter_envify

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  lint: ^1.8.1
  test: ^1.21.0

scripts: ../derry.yaml
