name: flutter_envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 1.0.0
homepage: https://github.com/tevfik1/flutter_envify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  build: ^2.3.1
  dotenv: ^3.0.0
  flutter_envify: ^1.0.0
  path: ^1.8.0
  source_gen: ^1.2.3

dev_dependencies:
  lint: ^1.8.1
  source_gen_test: ^1.0.4
  test: ^1.21.0

scripts: ../derry.yaml
