name: example
version: 0.0.1
description: An example for envify.

publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_envify: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_envify_generator:
    path: ../../flutter_envify_generator
